name:                ursus-maritimus-dataGen
version:             0.1.0.0
github:              "githubuser/ursus-maritimus-dataGen"
license:             BSD3
author:              "Sagi Fogel"
maintainer:          "sagi.fogel@gmail.com"
copyright:           "2018 Sagi Fogel"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ursus-maritimus-dataGen#readme>

dependencies:
- base >= 4.7 && < 5
- pipes
- containers
- text
- process-streaming
- bytestring
- process
- fake
- yaml
- time

library:
  source-dirs: src

executables:
  ursus-maritimus-dataGen-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ursus-maritimus-dataGen
    - pipes
    - text
    - process-streaming
    - bytestring
    - process
    - fake
    - yaml
    - time

tests:
  ursus-maritimus-dataGen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dataGen
